### ISSUE TITLE
Compilation error on log.info() after update to 5.2.0 

### ISSUE THREAD

**Issue by yhuriez** [danthorpe/Operations#937]
Hello,

I've updated my project to ProcedureKit v5.2.0 (from 4.5.0) and since when my logs don't work inside any Procedure. 
For instance when I write :`log.verbose("Some log")`, I get the compilation error :`Cannot call value of non-function type 'LogChannel'`. The same happens for log.error, log.info etc.

Is there a new configuration / way to do basic logging in Procedure ?

Thank you by advance for your time.

**Comment by danthorpe** [comment]
Hi @Deeplightened - this is one of the breaking changes with v5 - but it's not too much changes for you. You need to replace:

```swift
log.verbose("Some log")
```

with:

```swift
log.verbose.message("Some log")
```

**Comment by yhuriez** [comment]
It works indeed :)
Thanks you for your time
